name: Deploy Demo App

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Safe Registry
        run: |
          echo "${{ secrets.SAFE_REGISTRY_PASSWORD }}" | \
          docker login registry.safe.internal \
            -u "${{ secrets.SAFE_REGISTRY_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t registry.safe.internal/demo-app:${{ env.IMAGE_TAG }} \
            .

      - name: Push image to safe registry
        run: |
          docker push registry.safe.internal/demo-app:${{ env.IMAGE_TAG }}

      - name: Clone GitOps repo
        run: |
          git clone https://${{ secrets.GITOPS_PAT }}@github.com/Shyaminda/safeDeploy-environment.git gitops

      - name: Update image in GitOps manifests
        run: |
          cd gitops/apps/demo-app
          sed -i "s|image: .*|image: registry.safe.internal/demo-app:${{ env.IMAGE_TAG }}|" deployment.yaml

      - name: Commit and push GitOps changes
        run: |
          cd gitops
          git config user.name "demo-app-ci"
          git config user.email "ci@safedeploy.local"
          git add .
          git commit -m "release(demo-app): ${{ env.IMAGE_TAG }}"
          git push